# The configuration of handling the schematic
# Under development and still not working
---
# Enable this features
# If false, the plugin will use build-in generation
enable: false
# Schematic list
# Here is the hints for you (Case sensitive):
#  - FILE_NAME*       (String):     The name of the folder (including .schematic)
#  - BLOCK_SPAWN      (String):     he type of block that will be needed to spawn player
#                                   Must be one. Eg. '115:3' - Indicating to black wool
#  - PERMISSION       (String):     The permission that will be needed for player to attempt to
#                                   use this schematic.
#  - DESCRIPTION*     (String):     You know what is this mean for right?
#  - RATING           (double):     This might be unimplemented yet but this usage are to count
#                                   Player rating on challenges.
#  - USE_CONFIG_CHEST (boolean):    Use the default chest in config.yml
#  - PASTE_ENTITIES   (boolean):    Still under development. But work on minecarts
#  - BIOME            (String):     The Biome of the island. Eg: 'Plains'
#  - DEFAULT**        (boolean):    Set the template to be default template
#  - Note: ' * ' means required
#          ' ** ' means required to be used once
# You can leave other variables to indicate that you don't want them
schematicList:
  # Schematic list
  schematic:
    # This is a key for your island
    default:
      # This is an example of the island name
      FILE_NAME: "island.schematic"
      # This island name
      NAME: "Default Island"
      # This is an example of a description
      # This will be used in sign and others (Must be not long 25 char, otherwise the sign will be empty)
      DESCRIPTION: "The cozy island"
      # Permission base
      PERMISSION: "is.create"
      # Rating
      RATING: 1.8
      # Biome
      BIOME: "Plains"
      # Default priority
      DEFAULT: true


