## Default Config for ASkyBlock
---
## Game Prefix.
Prefix: "&c[&r&6Sky&bBlock&c]&r"
## Max islands homes
# You will have to set this as digit and will be used
# On island!
maxhome: 1
## Allow debugging - Remember this is for Developers only!
debug: false
## Allow to get Updates 
updater: false

## Chat Formattin
chat:
  # Use chat formatting such as &7 will return to ยง7
  UCFormatting: true

## Island Schematic 
schematic:
  # Use schematic for the best result
  # It still in development
  enabled: false
  # The loaded schematic, no need .schematic
  # You must put schematic files to `schematic/`
  # folder to load it.
  loaded: "harder, double, island, nether"
  # Main schematic, your choice
  # If loaded schematic doest exsits
  # It will using default schematic `island`
  main: "island"

## Island part
island:
  # Size of the island, You will have to set this
  #   if islandSize = 200, the size of island will be 100
  #   More easy if you use calculator `200 / 2` == 100
  #   Minimum: 50
  islandSize: 200
  # Island Hieght
  #   You can use this as island High
  #   Minimum: 20
  islandHieght: 60
  # Restricted commands in Island / SkyBlock
  #   level. You must respect the command format
  #   Such as `/example1, /example2`
  restrictedCommands: "/fly, /sell, /sg"
  # Island reset
  # You can use -1 for unlimited island reset
  resetPerPlayer: 3
  # Island addMember time out
  #   You can use -1 for unlimited time but 
  #   Recommeded 20 seconds
  timeOut: 20
  # Island companion names
  #   Your passion to add this or nor
  #   Syantax: "&aFood?, &eEmergency Food?, &cYour Pet!"
  companionNames: "&aFood?, &eEmergency Food?, &cYour Pet!"
  # Island Biome
  #   Your choice to 
  # Items that will be in the chest when the player starts an island
  # Must be in Nukkit Item format. Format is <ID>:<Qty> or <ID>:<Data>:<Qty>
  # Use <Data> to set the durability of a item or to select sub-items/colors.  
  #
  # Spawn EGGs is not available yet! do not put I warned you :P
  #
  # Check console for errors and guidance after reloading configuration
  chestItems: 'ICE:2 MELON:1 TORCH:2 BONE:1 LAVA_BUCKET:1 PUMPKIN_SEEDS:1 SUGAR_CANE:1 RED_MUSHROOM:1 BROWN_MUSHROOM:1 CACTUS:1 BREAD:1 WHEAT:1 LEATHER_BOOTS:1 LEATHER_HELMET:1 LEATHER_CHESTPLATE:1 LEATHER_LEGGINGS:1'

## Main lobby
lobby:
  # The location of lobby 
  lobbyX: 50
  lobbyY: 90
  lobbyZ: 50
  world: "world"

## Database
# Recomended to NOT change this in game
database:
  ## Choose the Provider that I given below
  # DATABASE - SQLite database configured at DBLib plugin
  # YAML - in .yaml files
  # UNKNOWN - .dat - My Database
  provider: DATABASE 
  # Configuration of DATABASE Connection:
  #  DBLIB  - default connection, defined in DbLib plugin
  #  SQLITE - custom sqlite file
  #  MYSQL  - custom MySql configuration
  connection: sqlite
  SQLite:
    # SQlite file name.
    # You can pick your name and
    # you no need to put `.db` at back
    file-name: database
  MySQL:
    port: 3306
    database: YourDataBase
    username: YourUserName
    password: 1234IsNotAGoodPassword
    host: localhost