name: "ASkyBlock"
version: "0.2.6"
author: larryTheCoder
api: ["1.0.0"]
main: com.larryTheCoder.ASkyBlock
load: POSTWORLD
website: http://github.com/larryTheCoder/ASkyBlock-Nukkit
author: "larryTheHarry"
depends: ["DbLib", "FastAsyncWorldEdit"]
permissions:
    is.bypass.wait:
     description: "bypass the reset timer / teleports"
     default: false    
    is.create:
     default: true
     description: "Create an island"
    is.command:
     default: true
     description: "SkyBlock main command"
    is.command.help:
     default: true
     description: "List all of ASkyBlock commands"
    is.command.kick:
     default: true
     description: "Kick a player from your island"   
    is.command.reset:
     default: true
     description: "Reset player island"
    is.command.leave:
     default: true
     description: "leave island"
    is.command.delete:
     default: true
     description: "Delete player island"  
    is.command.reject:
     default: true
     description: "Reject an invitation"   
    is.command.accept:
     default: true
     description: "accept an invitation"
    is.command.invite:
     default: true
     description: "Invite a player who didnt have a Team"
    is.command.create:
     default: true
     description: "Create a new island"  

    is.command.info:
     default: true
     description: "get the players island info"
    # Admin Island Command
    is.admin.generate:
     default: op
     description: "Generate a new island world"
    is.admin.kick:
     default: op
     description: "Kick a player from island world"
    # V.I.P permissions
    is.vip:
     default: op
     description: "Add a VIP full permissions of commands"
