name: "ASkyBlock"
version: "v0.1.1"
author: larryTheCoder
api: ["1.0.0"]
main: larryTheCoder.ASkyBlock
load: POSTWORLD
website: http://github.com/larryTheCoder/ASkyBlock-Nukkit
author: "larryTheHarry"

permissions:
    is.bypass.wait:
     description: "bypass the reset timer"
     default: false    
    is.create:
     default: true
     description: "Create an island"
    is.command:
     default: true
     description: "SkyBlock main command"
    is.command.help:
     default: true
     description: "List all of ASkyBlock commands"
    is.command.kick:
     default: true
     description: "Kick a player from your island"   
    is.command.reset:
     default: true
     description: "Reset player island"
    is.format:
     default: true
     description: "Reset player island"     
    # Admin Island Command
    is.admin.generate:
     default: op
     description: "Generate a new island world"
    is.admin.kick:
     default: op
     description: "Kick a player from island world"
